version: "2"

linters:
  default: all
  disable:
    - depguard
    - dogsled
    - exhaustruct
    - godot
    - noinlineerr
    - nolintlint
    - wsl # deprecated

  settings:
    cyclop:
      max-complexity: 15
    gomoddirectives:
      replace-local: true
    gosec:
      excludes:
        - G204
        - G301
        - G306
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
    lll:
      line-length: 150
    revive:
      rules:
        - name: package-comments
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1022
    varnamelen:
      ignore-names:
        - tt
        - ok
        - tx
        - id
        - db
        - to
        - i
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      case-max-lines: 1
      enable:
        - err
    wrapcheck:
      ignore-sigs:
        - .WithStack(
        - github.com/logica0419/coding-kubernetes

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/logica0419/coding-kubernetes)
        - blank
