name: Actions CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Actions
        uses: reviewdog/action-actionlint@v1
        with:
          fail_level: any
